"""Capture active core stat definitions without flattening interpolation."""
import argparse
import json
import re
import subprocess
from pathlib import Path
from thug_q import uncomment, physics_tables, lookup, stat_definition


def extract(upstream):
    g, s = physics_tables((upstream / 'Scripts/game/skater/physics.q').read_text())
    core = uncomment((upstream / 'Code/Sk/Components/SkaterCorePhysicsComponent.cpp').read_text())
    names = sorted(set(re.findall(r'GetScriptedStat\(CRCD\([^,]+,\s*"([^"]+)"', core)))
    entries, unresolved = [], []
    for name in names:
        try:
            definition = stat_definition(lookup(name, g, s), g)
        except KeyError:
            unresolved.append(name)
            continue
        entries.append({'name': name, **definition})
    commit = subprocess.check_output(['git', '-C', str(upstream), 'rev-parse', 'HEAD'], text=True).strip()
    return {'upstream_commit': commit, 'source': 'Scripts/game/skater/physics.q',
            'parameters': entries, 'unresolved_core_references': unresolved}


def header(data):
    def f(value):
        return repr(float(value)) + 'f'
    rows = ['// Generated by tools/extract_thug_stats.py; do not edit.',
            'static const NamedStat kStats[] = {']
    for p in data['parameters']:
        fields = [f(p['low']), f(p['high']), str(p['stat_index']),
                  str(int('switch' in p)), *(f(x) for x in p.get('switch', [1, 1])),
                  str(int('diff' in p)), *(f(x) for x in p.get('diff', [1, 1])),
                  str(int('limit' in p)), f(p.get('limit', 0))]
        rows.append('    {"' + p['name'] + '", {' + ', '.join(fields) + '}},')
    return '\n'.join(rows + ['};', ''])


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('upstream', type=Path)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[1]
    data = extract(args.upstream)
    outputs = {root / 'native/thug_adapter/config/thug_scripted_stats.json': json.dumps(data, indent=2) + '\n',
               root / 'native/thug_adapter/src/thug_scripted_stats.inc': header(data)}
    for path, text in outputs.items():
        if args.check:
            if path.read_text() != text:
                raise SystemExit('Captured data differs: ' + str(path))
        else:
            path.write_text(text)
    print(f"Captured {len(data['parameters'])} active core stat definitions; unresolved: {data['unresolved_core_references']}")
